name: Release Run

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # needed to create a GitHub Release + upload assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip & install deps
        run: |
          python -m pip install -U pip
          python -m pip install pyyaml jsonschema

      - name: Validate scenario
        run: python -m dutchbay_v13.validate dutchbay_v13/inputs/scenarios/release_case.yaml

      - name: Run IRR scenario (CSV + JSON)
        run: |
          python -m dutchbay_v13 --mode irr \
            --config dutchbay_v13/inputs/scenarios/release_case.yaml \
            --out _out --fmt csv

      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.ref_name }}
          path: _out/*

      - name: Create GitHub Release and attach artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            Includes scenario outputs (summary.json and results CSV).
          files: |
            _out/*