from __future__ import annotations
from pathlib import Path
from typing import Optional

def build_pdf_report(outdir: str | Path = "outputs", html_path: str | Path | None = None) -> Path:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    html = Path(html_path) if html_path else (outdir / "report.html")
    pdf_path = outdir / "report.pdf"

    # Try WeasyPrint (HTML -> PDF)
    try:
        from weasyprint import HTML  # type: ignore
        HTML(filename=str(html)).write_pdf(str(pdf_path))
        return pdf_path
    except Exception:
        pass

    # Fallback: ReportLab compact PDF
    try:
        from reportlab.lib.pagesizes import A4  # type: ignore
        from reportlab.pdfgen import canvas  # type: ignore
        from reportlab.lib.units import cm  # type: ignore
        from reportlab.lib.utils import ImageReader  # type: ignore
        c = canvas.Canvas(str(pdf_path), pagesize=A4)
        W, H = A4
        y = H - 2*cm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(2*cm, y, "DutchBay V13 – Summary Report")
        y -= 1.2*cm

        def draw_img(p: Path, title: str):
            nonlocal y
            if not p.exists():
                return
            c.setFont("Helvetica", 11)
            c.drawString(2*cm, y, title)
            y -= 0.6*cm
            img = ImageReader(str(p))
            iw, ih = img.getSize()
            maxw = W - 4*cm
            scale = min(maxw/iw, 8*cm/ih)
            c.drawImage(img, 2*cm, y-ih*scale, width=iw*scale, height=ih*scale, preserveAspectRatio=True, mask='auto')
            y -= ih*scale + 0.8*cm

        draw_img(outdir / "tornado.png", "Tornado (Sensitivity)")
        draw_img(outdir / "pareto.png", "Pareto Frontier (IRR vs DSCR)")

        c.setFont("Helvetica", 10)
        c.drawString(2*cm, 1.5*cm, "Generated by dutchbay_v13.report_pdf.build_pdf_report")
        c.showPage()
        c.save()
        return pdf_path
    except Exception as e:
        raise RuntimeError("PDF generation failed. Install extras: pip install .[pdf]") from e